// @vitest-environment jsdom
import {afterAll,afterEach,expect,it} from 'vitest';
import {act,createElement,type ReactElement} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import axe from 'axe-core';
import {Today} from './Today';
import {Ask} from './Ask';
import {Commitments} from './Commitments';
import {WeeklyReview} from './WeeklyReview';
import {MemoryInspector} from './MemoryInspector';
import {MemoryInbox} from './MemoryInbox';
import {AuditLog} from './AuditLog';
import {KeyboardUser,accessibleName,describe as described,tabOrder,type Step} from './testing/keyboard';
import {askAnsweredProps,askEmptyProps,commitmentsProps,id,inboxDecision,memoryInboxProps,memoryInspectorProps,todayProps,
  weeklyReviewProps} from './testing/screens';
import {AUDIT_ACTOR,auditLog} from './testing/audit';

/**
 * Accessibility of the core views (design non-functional "accessibility";
 * CRT-UX-14-A): automated checks and a keyboard-only walkthrough of Today, Ask,
 * Commitments, Weekly Review, Memory Inspector and Memory Inbox.
 *
 * Each screen is rendered by React into a real DOM (jsdom), exactly as its page
 * renders it, and then:
 *
 *  - axe-core, the engine behind the common browser accessibility checkers, runs
 *    every WCAG 2 A/AA and best-practice rule it has over the document; a
 *    critical violation fails the suite (and so does a serious one). Colour
 *    contrast is the one rule it cannot run without a layout engine; the
 *    grayscale-safe label system has its own test (`Labels.test.ts`).
 *  - a keyboard-only user (`testing/keyboard.ts`: Tab, Shift+Tab, typing, Enter,
 *    Space and Arrow Down, each with the browser's native default action, and no
 *    pointer at all) completes every core task of the screen.
 *
 * The walkthrough transcript and the axe summary are written to
 * `test-results/accessibility/`, the CI artifact the design requires beside the
 * automated checks.
 */

(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
// Each scenario scans several complete DOM states and walks every keyboard task.
// Under the CI unit stage's four workers, the default 5s expires mid-walk and
// cleanup clears the DOM while that scenario is still running, corrupting the
// next screen's axe result. Keep a bounded integration budget without dropping
// any audit, keyboard action, or assertion.
const CORE_VIEW_TIMEOUT_MS=20_000;
const ARTIFACT_DIRECTORY=resolve('test-results/accessibility');
const report:{screens:Record<string,{states:Record<string,{violations:Array<{id:string;impact:string|null;nodes:number}>;passes:number}>;
  tasks:Array<{task:string;completed:boolean;steps:Step[];navigations:string[]}>}>}={screens:{}};

let root:Root|null=null;
const originalFetch=globalThis.fetch;
afterEach(()=>{act(()=>root?.unmount());root=null;document.body.innerHTML='';globalThis.fetch=originalFetch;});
afterAll(()=>{
  mkdirSync(ARTIFACT_DIRECTORY,{recursive:true});
  writeFileSync(resolve(ARTIFACT_DIRECTORY,'report.json'),JSON.stringify({
    criterion:'CRT-UX-14-A',axeVersion:axe.version,generatedAt:new Date().toISOString(),...report},null,2));
  const lines=['# Keyboard-only walkthrough of the core views','',
    'Generated by `apps/web/components/Accessibility.test.ts` (CRT-UX-14-A). No pointer is used: every step is a key.',''];
  for(const [screen,entry] of Object.entries(report.screens)){
    lines.push('## '+screen,'');
    for(const [state,result] of Object.entries(entry.states)){
      lines.push('- axe, '+state+': '+result.violations.length+' violations ('+result.passes+' rules passed)');
    }
    for(const task of entry.tasks){
      lines.push('','### '+task.task+(task.completed?'':' (NOT COMPLETED)'),'');
      task.steps.forEach((step,index)=>lines.push((index+1)+'. `'+step.key+'` on '+step.target+' → '+step.outcome));
    }
    lines.push('');
  }
  writeFileSync(resolve(ARTIFACT_DIRECTORY,'keyboard-walkthrough.md'),lines.join('\n'));
});

async function mount(element:ReactElement){
  if(root){const previous=root;act(()=>previous.unmount());root=null;}
  document.body.innerHTML='';
  // The served document declares its language (pages/_document.tsx); so does this one.
  document.documentElement.lang=/<Html lang="([a-z-]+)">/.exec(readFileSync(resolve('apps/web/pages/_document.tsx'),'utf8'))?.[1]??'';
  document.title='Uai';
  const container=document.createElement('div');
  container.id='__next';
  document.body.appendChild(container);
  root=createRoot(container);
  await act(async()=>{root!.render(element);});
}

function entry(screen:string){return report.screens[screen]??=(report.screens[screen]={states:{},tasks:[]});}

/** axe over the whole document: no critical and no serious violation. */
async function audit(screen:string,state:string){
  const results=await axe.run(document,{rules:{'color-contrast':{enabled:false}}});
  entry(screen).states[state]={violations:results.violations.map(violation=>({id:violation.id,impact:violation.impact??null,nodes:violation.nodes.length})),
    passes:results.passes.length};
  const blocking=results.violations.filter(violation=>violation.impact==='critical'||violation.impact==='serious');
  expect(blocking.map(violation=>violation.id+': '+violation.help+' at '+violation.nodes.map(node=>node.target.join(' ')).join(', ')),
    screen+' / '+state).toEqual([]);
  expect(results.passes.length,screen+' / '+state).toBeGreaterThan(10);
  return results;
}

/** Structure every screen shares: a first-focus skip link to a focusable main
 * landmark, one h1, no positive tabindex, a name for every focusable element, and
 * a tab order that runs from the top to off the page without a trap. */
async function structure(screen:string){
  const order=tabOrder(document);
  expect(order.length,screen).toBeGreaterThan(3);
  expect(order.filter(element=>Number(element.getAttribute('tabindex')??0)>0),screen).toEqual([]);
  for(const element of order)expect(accessibleName(element),screen+': '+described(element)+' '+element.outerHTML.slice(0,120)).not.toBe('');
  expect(document.querySelectorAll('main').length).toBe(1);
  expect(document.querySelectorAll('h1').length).toBe(1);
  const user=new KeyboardUser(document);
  const first=user.tab();
  expect(first?.textContent).toBe('Skip to content');
  await act(async()=>user.press('Enter'));
  expect(document.activeElement?.tagName,screen+': the skip link moves focus to the main landmark').toBe('MAIN');
  // From the top, Tab visits every focusable element once and then leaves the page.
  const visited:HTMLElement[]=[];
  const walker=new KeyboardUser(document);
  for(let element=walker.tab();element;element=walker.tab())visited.push(element);
  expect(visited,screen+': no keyboard trap').toEqual(order);
  expect(new Set(visited).size).toBe(visited.length);
  // And Shift+Tab walks back the same way.
  const back:HTMLElement[]=[];
  for(let element=walker.shiftTab();element;element=walker.shiftTab())back.push(element);
  expect(back.reverse()).toEqual(order);
}

async function task(screen:string,name:string,run:(user:KeyboardUser)=>Promise<void>){
  const user=new KeyboardUser(document);
  const record={task:name,completed:false,steps:user.steps,navigations:user.navigations};
  entry(screen).tasks.push(record);
  await run(user);
  record.completed=true;
}
const named=(pattern:RegExp)=>(element:HTMLElement)=>pattern.test(accessibleName(element));
async function press(user:KeyboardUser,key:'Enter'|' '){await act(async()=>{user.press(key);await new Promise(done=>setTimeout(done,0));});}

// ---------------------------------------------------------------------------

it('Today: automated checks pass and every core task completes from the keyboard alone',async()=>{
  await mount(createElement(Today,todayProps));
  await audit('Today','briefing');
  await structure('Today');
  await task('Today','Find out why an item is in today\'s briefing',async user=>{
    const why=user.tabTo(named(/^Why is this here\?/))!;
    expect(why,'the why-surfaced disclosure is reachable').not.toBeNull();
    await press(user,'Enter');
    expect((why.parentElement as HTMLDetailsElement).open).toBe(true);
    // Its ranking table is now in the reading order.
    expect(why.parentElement!.querySelector('table caption')?.textContent).toBe('What it was ranked by (0 to 1)');
  });
  await task('Today','Open the sources behind an item',async user=>{
    const sources=user.tabTo(named(/^Why\? \/ Sources/))!;
    expect(sources).not.toBeNull();
    await press(user,'Enter');
    expect((sources.parentElement as HTMLDetailsElement).open).toBe(true);
    expect(sources.parentElement!.textContent).toContain('I will send Daniel the signed lease.');
  });
  await task('Today','Inspect and correct the belief behind an item',async user=>{
    expect(user.tabTo(named(/^Inspect Commitment to Daniel/))).not.toBeNull();
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toBe('/memory/inspector/proposition/'+id(301));
    expect(user.tabTo(named(/^Correct Commitment to Daniel/))).not.toBeNull();
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toBe('/memory/correct/proposition/'+id(301));
  });
  await task('Today','Read what the certainty labels mean',async user=>{
    const key=user.tabTo(named(/^What the labels mean$/))!;
    expect(key).not.toBeNull();
    await press(user,'Enter');
    expect((key.parentElement as HTMLDetailsElement).open).toBe(true);
  });
  await mount(createElement(Today,{state:'loading',briefing:null,why:{}}));
  await audit('Today','loading');
  expect(document.querySelector('[role=status]')?.textContent).toContain('Loading today');
},CORE_VIEW_TIMEOUT_MS);

it('Ask: automated checks pass and every core task completes from the keyboard alone',async()=>{
  await mount(createElement(Ask,askEmptyProps));
  await audit('Ask','empty with example questions');
  await structure('Ask');
  await task('Ask','Ask a question and hear that it is being answered',async user=>{
    const field=user.tabTo(named(/^Your question$/))!;
    expect(field.getAttribute('type')).toBe('search');
    user.type('What did I promise Daniel?');
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toBe('/ask?q=What+did+I+promise+Daniel%3F');
    expect(document.querySelector('[role=status]')?.textContent).toBe('Classifying the requested answer type…');
  });
  await task('Ask','Ask one of the example questions',async user=>{
    expect(user.tabTo(named(/^What did I promise Daniel\?$/))).not.toBeNull();
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toBe('/ask?q='+encodeURIComponent('What did I promise Daniel?'));
  });
  await mount(createElement(Ask,askAnsweredProps));
  await audit('Ask','answered');
  expect(document.querySelector('[role=status]')?.textContent).toBe('Answer ready: 2 statements.');
  await task('Ask','Check why a statement is said, and open its source',async user=>{
    expect(user.tabTo(named(/^Source 1: conversation/))).not.toBeNull();
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toBe('/sources?evidence='+id(400));
    const why=user.tabTo(named(/^Why\? \/ Sources/))!;
    expect(why).not.toBeNull();
    await press(user,'Enter');
    expect((why.parentElement as HTMLDetailsElement).open).toBe(true);
  });
  await task('Ask','Open how the answer was made',async user=>{
    expect(user.tabTo(named(/^How this answer was made/))).not.toBeNull();
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toBe('/answers/'+id(2));
  });
  await mount(createElement(Ask,{...askEmptyProps,state:'refused',refusal:'CONTEXT_READ_DENIED'}));
  await audit('Ask','refused');
  expect(document.querySelector('[role=alert]')?.textContent).toContain('refused');
},CORE_VIEW_TIMEOUT_MS);

it('Commitments: automated checks pass and every core task completes from the keyboard alone',async()=>{
  await mount(createElement(Commitments,commitmentsProps));
  await audit('Commitments','open, overdue and contested');
  await structure('Commitments');
  await task('Commitments','Filter by person, including resolved commitments',async user=>{
    expect(user.tabTo(named(/^Person$/))).not.toBeNull();
    user.arrowDown();
    expect(user.tabTo(named(/Include resolved commitments/))).not.toBeNull();
    await press(user,' ');
    expect((user.current as HTMLInputElement).checked).toBe(true);
    expect(user.tabTo(named(/^Apply filters$/))).not.toBeNull();
    await press(user,'Enter');
    const [path,query]=user.navigations.at(-1)!.split('?');
    expect(path).toBe('/commitments');
    const filters=new URLSearchParams(query);
    expect(filters.get('person')).toBe(id(21));
    expect(filters.getAll('includeResolved')).toEqual(['false','true']);
  });
  await task('Commitments','Inspect and correct a commitment',async user=>{
    expect(user.tabTo(named(/^Inspect/))).not.toBeNull();
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toBe('/memory/inspector/proposition/'+id(41));
    expect(user.tabTo(named(/^Correct/))).not.toBeNull();
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toBe('/memory/correct/proposition/'+id(41));
  });
  await mount(createElement(Commitments,{...commitmentsProps,state:'loading',view:null}));
  await audit('Commitments','loading');
},CORE_VIEW_TIMEOUT_MS);

it('Weekly Review: automated checks pass and every core task completes from the keyboard alone',async()=>{
  await mount(createElement(WeeklyReview,weeklyReviewProps));
  await audit('Weekly Review','review');
  await structure('Weekly Review');
  await task('Weekly Review','Choose another week',async user=>{
    expect(user.tabTo(named(/^Week starting$/))).not.toBeNull();
    user.type('2026-03-09');
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toBe('/weekly-review?weekStart=2026-03-09');
  });
  await task('Weekly Review','Inspect and correct the memory behind a statement',async user=>{
    expect(user.tabTo(named(/^Inspect Family/))).not.toBeNull();
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toBe('/memory/inspector/proposition/'+id(1));
    expect(user.tabTo(named(/^Correct Family/))).not.toBeNull();
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toBe('/memory/correct/proposition/'+id(1));
  });
  await mount(createElement(WeeklyReview,{weekStart:'2026-03-02',review:null,loading:true}));
  await audit('Weekly Review','loading');
},CORE_VIEW_TIMEOUT_MS);

it('Memory Inspector: automated checks pass and every core task completes from the keyboard alone',async()=>{
  await mount(createElement(MemoryInspector,memoryInspectorProps));
  await audit('Memory Inspector','belief');
  await structure('Memory Inspector');
  await task('Memory Inspector','Correct the inspected belief',async user=>{
    expect(user.tabTo(named(/^Correct this belief$/))).not.toBeNull();
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toBe('/memory/correct/proposition/'+id(1));
  });
  await task('Memory Inspector','Inspect the competing value and the connected thread',async user=>{
    expect(user.tabTo(named(/^inspect the other value$/))).not.toBeNull();
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toBe('/memory/inspector/proposition/'+id(8));
    expect(user.tabTo(named(/^Daniel payment$/))).not.toBeNull();
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toBe('/memory/threads/'+id(18));
  });
  await task('Memory Inspector','Reveal the advanced identifiers',async user=>{
    const identifiers=user.tabTo(named(/^Identifiers$/))!;
    expect(identifiers).not.toBeNull();
    await press(user,'Enter');
    expect((identifiers.parentElement as HTMLDetailsElement).open).toBe(true);
    expect(identifiers.parentElement!.textContent).toContain(id(1));
  });
  await mount(createElement(MemoryInspector,{state:'not-found',inspector:null}));
  await audit('Memory Inspector','not found');
},CORE_VIEW_TIMEOUT_MS);

it('Memory Inbox: automated checks pass and every core task completes from the keyboard alone',async()=>{
  const requests:Array<{url:string;init:RequestInit}>=[];
  globalThis.fetch=(async(url:string,init:RequestInit)=>{requests.push({url,init});
    return new Response(JSON.stringify(inboxDecision),{status:200,headers:{'content-type':'application/json'}});}) as typeof fetch;
  await mount(createElement(MemoryInbox,memoryInboxProps));
  await audit('Memory Inbox','card within budget');
  await structure('Memory Inbox');
  await task('Memory Inbox','Read why a question is asked and what each choice changes',async user=>{
    const why=user.tabTo(named(/^Why you are seeing this/))!;
    expect(why).not.toBeNull();
    await press(user,'Enter');
    expect((why.parentElement as HTMLDetailsElement).open).toBe(true);
    expect(why.parentElement!.textContent).toContain('Asked within today’s attention budget.');
    // Back to the choices: each announces what it will change.
    let choice:HTMLElement|null=null;
    for(let element=user.shiftTab();element;element=user.shiftTab())if(/^Confirm repayment/.test(accessibleName(element))){choice=element;break;}
    expect(choice).not.toBeNull();
    expect(document.getElementById(choice!.getAttribute('aria-describedby')!)?.textContent)
      .toBe('What will change: Records that the ₪60 transfer repaid this obligation.');
  });
  await task('Memory Inbox','Answer a card',async user=>{
    expect(user.tabTo(named(/^Confirm repayment for Possible Daniel repayment$/))).not.toBeNull();
    await press(user,'Enter');
    expect(requests).toHaveLength(1);
    expect(requests[0]!.url).toBe('/api/platform/memory/inbox/cards/'+id(1)+'/decide');
    expect(requests[0]!.init.method).toBe('POST');
    expect(JSON.parse(String(requests[0]!.init.body))).toEqual({choiceId:'confirm_repayment'});
    const headers=requests[0]!.init.headers as Record<string,string>;
    expect(headers['x-purpose']).toBe('memory.inbox');
    expect(headers['idempotency-key']).toMatch(/^[0-9a-f]{32}$/);
    // The result is announced, and the answered card has left the list.
    const recorded=document.querySelector('section[aria-labelledby=decided]');
    expect(recorded?.getAttribute('role')).toBe('status');
    expect(recorded?.textContent).toContain('Possible Daniel repayment: Confirm repayment.');
    expect(document.body.textContent).not.toContain('Why it matters');
  });
  await audit('Memory Inbox','answer recorded');
  await mount(createElement(MemoryInbox,{view:{...memoryInboxProps.view,cards:[],deferredCount:0}}));
  await audit('Memory Inbox','empty');
},CORE_VIEW_TIMEOUT_MS);

it('Audit log: automated checks pass, and it is read and filtered from the keyboard alone',async()=>{
  await mount(createElement(AuditLog,{log:auditLog(),actorId:AUDIT_ACTOR}));
  await audit('Audit log','events with a refused change and a deletion');
  await structure('Audit log');
  await task('Audit log','Filter the log by kind',async user=>{
    expect(user.tabTo(named(/^Kind$/))).not.toBeNull();
    user.arrowDown();
    expect(user.tabTo(named(/^Show events$/))).not.toBeNull();
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toBe('/ops/audit?eventKind=READ&purpose=&objectType=&objectId=');
  });
  await task('Audit log','Scroll the event table and show one object\'s events',async user=>{
    const region=user.tabTo(element=>element.getAttribute('role')==='region')!;
    expect(region).not.toBeNull();
    expect(accessibleName(region)).toBe('Audit event table (scrolls sideways)');
    expect(user.tabTo(named(/^Events for this object/))).not.toBeNull();
    await press(user,'Enter');
    expect(user.navigations.at(-1)).toMatch(/^\/ops\/audit\?objectType=audit_events&objectId=/);
  });
},CORE_VIEW_TIMEOUT_MS);

it('no core view responds to a pointer alone: every handler sits on a native control', ()=>{
  for(const file of ['Today','Ask','Commitments','WeeklyReview','MemoryInspector','MemoryInbox','WhySources','BeliefLinks','Labels',
    'MemoryChrome','Shell','Navigation','AuditLog']){
    const source=readFileSync(resolve('apps/web/components',file+'.tsx'),'utf8');
    expect(source,file).not.toMatch(/on(Mouse|Pointer|DoubleClick|Drag|Touch)[A-Z][a-z]*=/);
    for(const match of source.matchAll(/<([A-Za-z]+)\b[^<>]*\bonClick=/g))expect(['button','a'],file+' <'+match[1]+'>').toContain(match[1]);
    expect(source,file).not.toMatch(/tabIndex=\{?["']?[1-9]/);
  }
});
